export const KEYBOARD = {
  rows: [
    ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', 'Backspace'],
    ['Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash', 'Delete'],
    ['CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter'],
    ['ShiftLeft', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'ShiftRight'],
    ['ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight', 'ArrowLeft', 'ArrowDown', 'ArrowRight', 'ControlRight'],
  ],

  keysChar:
    ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal',
      'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash', 'KeyA',
      'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN',
      'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'Space', 'ArrowLeft', 'ArrowDown', 'ArrowRight', 'Tab', 'Enter', 'Backspace', 'Delete',
    ],

  keys: {
    Backquote: {
      value: '`',
      valuePressShift: '~',
      valueRu: 'ё',
      valuePressShiftRu: 'Ё',
      styleCSS: 'key',
    },
    Digit1: {
      value: '1',
      valuePressShift: '!',
      valueRu: '1',
      valuePressShiftRu: '!',
      styleCSS: 'key',
    },
    Digit2: {
      value: '2',
      valuePressShift: '@',
      valueRu: '2',
      valuePressShiftRu: '&quot;',
      styleCSS: 'key',
    },
    Digit3: {
      value: '3',
      valuePressShift: '#',
      valueRu: '3',
      valuePressShiftRu: '№',
      styleCSS: 'key',
    },
    Digit4: {
      value: '4',
      valuePressShift: '$',
      valueRu: '4',
      valuePressShiftRu: ';',
      styleCSS: 'key',
    },
    Digit5: {
      value: '5',
      valuePressShift: '%',
      valueRu: '5',
      valuePressShiftRu: '%',
      styleCSS: 'key',
    },
    Digit6: {
      value: '6',
      valuePressShift: '^',
      valueRu: '6',
      valuePressShiftRu: ':',
      styleCSS: 'key',
    },
    Digit7: {
      value: '7',
      valuePressShift: '&amp;',
      valueRu: '7',
      valuePressShiftRu: '?',
      styleCSS: 'key',
    },
    Digit8: {
      value: '8',
      valuePressShift: '*',
      valueRu: '8',
      valuePressShiftRu: '*',
      styleCSS: 'key',
    },
    Digit9: {
      value: '9',
      valuePressShift: '(',
      valueRu: '9',
      valuePressShiftRu: '(',
      styleCSS: 'key',
    },
    Digit0: {
      value: '0',
      valuePressShift: ')',
      valueRu: '0',
      valuePressShiftRu: ')',
      styleCSS: 'key',
    },
    Minus: {
      value: '-',
      valuePressShift: '_',
      valueRu: '-',
      valuePressShiftRu: '_',
      styleCSS: 'key',
    },
    Equal: {
      value: '=',
      valuePressShift: '+',
      valueRu: '=',
      valuePressShiftRu: '+',
      styleCSS: 'key',
    },
    Backspace: {
      value: 'Backspace',
      valuePressShift: 'Backspace',
      valueRu: 'Backspace',
      valuePressShiftRu: 'Backspace',
      styleCSS: 'key key--backspace',
    },
    Tab: {
      value: 'Tab',
      valuePressShift: 'Tab',
      valueRu: 'Tab',
      valuePressShiftRu: 'Tab',
      styleCSS: 'key key--tab',
    },
    KeyQ: {
      value: 'q',
      valuePressShift: 'Q',
      valueRu: 'й',
      valuePressShiftRu: 'Й',
      styleCSS: 'key',
    },
    KeyW: {
      value: 'w',
      valuePressShift: 'W',
      valueRu: 'ц',
      valuePressShiftRu: 'Ц',
      styleCSS: 'key',
    },
    KeyE: {
      value: 'e',
      valuePressShift: 'E',
      valueRu: 'у',
      valuePressShiftRu: 'У',
      styleCSS: 'key',
    },
    KeyR: {
      value: 'r',
      valuePressShift: 'R',
      valueRu: 'к',
      valuePressShiftRu: 'К',
      styleCSS: 'key',
    },
    KeyT: {
      value: 't',
      valuePressShift: 'T',
      valueRu: 'е',
      valuePressShiftRu: 'Е',
      styleCSS: 'key',
    },
    KeyY: {
      value: 'y',
      valuePressShift: 'Y',
      valueRu: 'н',
      valuePressShiftRu: 'Н',
      styleCSS: 'key',
    },
    KeyU: {
      value: 'u',
      valuePressShift: 'U',
      valueRu: 'г',
      valuePressShiftRu: 'Г',
      styleCSS: 'key',
    },
    KeyI: {
      value: 'i',
      valuePressShift: 'I',
      valueRu: 'ш',
      valuePressShiftRu: 'Ш',
      styleCSS: 'key',
    },
    KeyO: {
      value: 'o',
      valuePressShift: 'O',
      valueRu: 'щ',
      valuePressShiftRu: 'Щ',
      styleCSS: 'key',
    },
    KeyP: {
      value: 'p',
      valuePressShift: 'P',
      valueRu: 'з',
      valuePressShiftRu: 'З',
      styleCSS: 'key',
    },
    BracketLeft: {
      value: '[',
      valuePressShift: '{',
      valueRu: 'х',
      valuePressShiftRu: 'Х',
      styleCSS: 'key',
    },
    BracketRight: {
      value: ']',
      valuePressShift: '}',
      valueRu: 'ъ',
      valuePressShiftRu: 'Ъ',
      styleCSS: 'key',
    },
    Backslash: {
      value: '\'',
      valuePressShift: '|',
      valueRu: '\'',
      valuePressShiftRu: '/',
      styleCSS: 'key',
    },
    Delete: {
      value: 'Del',
      valuePressShift: 'Del',
      valueRu: 'Del',
      valuePressShiftRu: 'Del',
      styleCSS: 'key key--del',
    },
    CapsLock: {
      value: 'CapsLock',
      valuePressShift: 'CapsLock',
      valueRu: 'CapsLock',
      valuePressShiftRu: 'CapsLock',
      styleCSS: 'key key--caps-lock',
    },
    KeyA: {
      value: 'a',
      valuePressShift: 'A',
      valueRu: 'ф',
      valuePressShiftRu: 'Ф',
      styleCSS: 'key',
    },
    KeyS: {
      value: 's',
      valuePressShift: 'S',
      valueRu: 'ы',
      valuePressShiftRu: 'Ы',
      styleCSS: 'key',
    },
    KeyD: {
      value: 'd',
      valuePressShift: 'D',
      valueRu: 'в',
      valuePressShiftRu: 'В',
      styleCSS: 'key',
    },
    KeyF: {
      value: 'f',
      valuePressShift: 'F',
      valueRu: 'а',
      valuePressShiftRu: 'А',
      styleCSS: 'key',
    },
    KeyG: {
      value: 'g',
      valuePressShift: 'G',
      valueRu: 'п',
      valuePressShiftRu: 'П',
      styleCSS: 'key',
    },
    KeyH: {
      value: 'h',
      valuePressShift: 'H',
      valueRu: 'р',
      valuePressShiftRu: 'Р',
      styleCSS: 'key',
    },
    KeyJ: {
      value: 'j',
      valuePressShift: 'J',
      valueRu: 'о',
      valuePressShiftRu: 'О',
      styleCSS: 'key',
    },
    KeyK: {
      value: 'k',
      valuePressShift: 'K',
      valueRu: 'л',
      valuePressShiftRu: 'Л',
      styleCSS: 'key',
    },
    KeyL: {
      value: 'l',
      valuePressShift: 'L',
      valueRu: 'д',
      valuePressShiftRu: 'Д',
      styleCSS: 'key',
    },
    Semicolon: {
      value: ';',
      valuePressShift: ':',
      valueRu: 'ж',
      valuePressShiftRu: 'Ж',
      styleCSS: 'key',
    },
    Quote: {
      value: '&#39;',
      valuePressShift: '&quot;',
      valueRu: 'э',
      valuePressShiftRu: 'Э',
      styleCSS: 'key',
    },
    Enter: {
      value: 'Enter',
      valuePressShift: 'Enter',
      valueRu: 'Enter',
      valuePressShiftRu: 'Enter',
      styleCSS: 'key key--enter',
    },
    KeyZ: {
      value: 'z',
      valuePressShift: 'Z',
      valueRu: 'я',
      valuePressShiftRu: 'Я',
      styleCSS: 'key',
    },
    KeyX: {
      value: 'x',
      valuePressShift: 'X',
      valueRu: 'ч',
      valuePressShiftRu: 'Ч',
      styleCSS: 'key',
    },
    KeyC: {
      value: 'c',
      valuePressShift: 'C',
      valueRu: 'с',
      valuePressShiftRu: 'С',
      styleCSS: 'key',
    },
    KeyV: {
      value: 'v',
      valuePressShift: 'V',
      valueRu: 'м',
      valuePressShiftRu: 'М',
      styleCSS: 'key',
    },
    KeyB: {
      value: 'b',
      valuePressShift: 'B',
      valueRu: 'и',
      valuePressShiftRu: 'И',
      styleCSS: 'key',
    },
    KeyN: {
      value: 'n',
      valuePressShift: 'N',
      valueRu: 'т',
      valuePressShiftRu: 'Т',
      styleCSS: 'key',
    },
    KeyM: {
      value: 'm',
      valuePressShift: 'M',
      valueRu: 'ь',
      valuePressShiftRu: 'Ь',
      styleCSS: 'key',
    },
    Comma: {
      value: ',',
      valuePressShift: '&lt;',
      valueRu: 'б',
      valuePressShiftRu: 'Б',
      styleCSS: 'key',
    },
    Period: {
      value: '.',
      valuePressShift: '&gt;',
      valueRu: 'ю',
      valuePressShiftRu: 'Ю',
      styleCSS: 'key',
    },
    Slash: {
      value: '/',
      valuePressShift: '?',
      valueRu: '.',
      valuePressShiftRu: ',',
      styleCSS: 'key',
    },
    ArrowUp: {
      value: '&uarr;',
      valuePressShift: '&uarr;',
      valueRu: '&uarr;',
      valuePressShiftRu: '&uarr;',
      styleCSS: 'key key--arrow-up',
    },
    ShiftRight: {
      value: 'Shift',
      valuePressShift: 'Shift',
      valueRu: 'Shift',
      valuePressShiftRu: 'Shift',
      styleCSS: 'key key--shift-right',
    },
    ShiftLeft: {
      value: 'Shift',
      valuePressShift: 'Shift',
      valueRu: 'Shift',
      valuePressShiftRu: 'Shift',
      styleCSS: 'key key--shift-left',
    },
    ControlLeft: {
      value: 'Ctrl',
      valuePressShift: 'Ctrl',
      valueRu: 'Ctrl',
      valuePressShiftRu: 'Ctrl',
      styleCSS: 'key key--ctrl-left',
    },
    MetaLeft: {
      value: 'Win',
      valuePressShift: 'Win',
      valueRu: 'Win',
      valuePressShiftRu: 'Win',
      styleCSS: 'key key--win',
    },
    AltLeft: {
      value: 'Alt',
      valuePressShift: 'Alt',
      valueRu: 'Alt',
      valuePressShiftRu: 'Alt',
      styleCSS: 'key key--alt-left',
    },
    Space: {
      value: ' ',
      valuePressShift: ' ',
      valueRu: ' ',
      valuePressShiftRu: ' ',
      styleCSS: 'key key--space',
    },
    AltRight: {
      value: 'Alt',
      valuePressShift: 'Alt',
      valueRu: 'Alt',
      valuePressShiftRu: 'Alt',
      styleCSS: 'key key--alt-right',
    },
    ArrowLeft: {
      value: '&larr;',
      valuePressShift: '&larr;',
      valueRu: '&larr;',
      valuePressShiftRu: '&larr;',
      styleCSS: 'key key--arrow-left',
    },
    ArrowDown: {
      value: '&darr;',
      valuePressShift: '&darr;',
      valueRu: '&darr;',
      valuePressShiftRu: '&darr;',
      styleCSS: 'key key--arrow-down',
    },
    ArrowRight: {
      value: '&rarr;',
      valuePressShift: '&rarr;',
      valueRu: '&rarr;',
      valuePressShiftRu: '&rarr;',
      styleCSS: 'key key--arrow-right',
    },
    ControlRight: {
      value: 'Ctrl',
      valuePressShift: 'Ctrl',
      valueRu: 'Ctrl',
      valuePressShiftRu: 'Ctrl',
      styleCSS: 'key key--ctrl-right',
    },
  },

};